version: '2'

services:
    nginx:
        image: nginx:alpine
        container_name: '${PROJECT_NAME}-nginx'
        volumes:
            - ./docker/nginx/dev/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/dev/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - app
        ports:
            - 80:80
        labels:
            project: ${PROJECT_NAME}

    app:
        image: '${PROJECT_NAME}-app'
        build: docker/app
        container_name: '${PROJECT_NAME}-app'
        ports:
            - 80
        environment:
            DB_DATABASE: 'thaidirectory'
            DB_USERNAME: 'postgres'
            DB_PASSWORD: 'postgres'
            DB_HOST: 'postgresdb'
        volumes:
            - .:/var/www
        links:
            - postgresdb
            - redis
        labels:
            project: ${PROJECT_NAME}

    postgresdb:
        image: postgres:9.5.3
        ports:
            - 5432:5432
        container_name: '${PROJECT_NAME}-postgresdb'
        environment:
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_USER: ${DATABASE_USER}
        volumes:
            - .data/postgres:/var/lib/postgresql/data
        labels:
            project: ${PROJECT_NAME}

    redis:
        image: redis
        container_name: '${PROJECT_NAME}-redis'
        volumes:
            - .data/redis:/data
        labels:
            project: ${PROJECT_NAME}

networks:
    default:
        external:
            name: ${NETWORK_NAME}

